### ISSUE TITLE
Bug on windows 

### ISSUE THREAD

**Issue by PrajwalM2212** [moremoban/moban#117]
moban is reported to be giving incorrect outputs in netlify.toml file on windows. https://github.com/coala/coala/pull/5881/files#diff-5db06fd2327543bbb72119cd1e5761cf 
It would be great if the problem is identified and fixed.

It is replacing 
```toml
[build]
  publish = "docs/_build/html"
  command = "pip install -r docs-requirements.txt && export PYTHONPATH=$(pwd) && python setup.py docs"  


../../templates/docs/netlify.toml.jj2

**Comment by chfw** [comment]
Cannot see the change. I need to be able to reproduce it before looking at it.

**Comment by jayvdb** [comment]
The file mentioned in coala/coala .moban.yaml refers to a symlink, and windows replaces the file contents with garbage from the symlink during the sync

**Comment by chfw** [comment]
with windows unit tests running, a number of issues were found:

#142 , #141

**Comment by chfw** [comment]
@PrajwalM2212 , what this problem again? 

did you create a symlink file on windows? docs/netlify.toml link to ../../templates/docs/netlify.toml.jj2

and moban replace the target with junk.

**Comment by chfw** [comment]
blocked because no way to reproduce it.

**Comment by jayvdb** [comment]
Probably already fixed, if we have a test case which uses a symlink created on Unix, and that symlink test is active on Windows.

**Comment by chfw** [comment]
According to this post: https://unix.stackexchange.com/questions/63172/does-windows-recognize-linuxs-symbolic-links, it seems Windows itself could distinguish linux symbolic link.

Hence, I am not sure if os.path.islink would be able to find out this is linux symbolic link.

**Comment by chfw** [comment]
please reference #251 , linux symbolic link is seen as a text file with the actual linked file inside it. hence, we would need some special utility so that moban can detect it as linux symlink on windows.

![screenshot 2019-03-07 at 21 46 17](https://user-images.githubusercontent.com/4280312/53991433-80605080-4122-11e9-92bf-0d5b9dd4de76.png)

**Comment by ayan-b** [comment]
@chfw isn't this issue solved by #251 & #254?

**Comment by chfw** [comment]
Nope, they are not resolve it. Both issues were found when I was looking at this issue. 

I do not think a unit test is possible for this issue either.

**Comment by chfw** [comment]
What I can do is to insert a warning note in our doc: saying: Never put a symblic link in your templates if you want to use it in windows.
