### ISSUE TITLE
Strip extra trailing new lines

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#13]
In https://github.com/moremoban/moban/pull/4, we kept the trailing blank line, which is good ..

but, it would be nice if after all operations, before the file is written, a final modification is made to ensure there is only one single trailing line feed.
i.e. no blank lines.

Otherwise, we need to remove trailing blank lines like https://github.com/moremoban/setupmobans/blob/78bcfbc/templates/gitignore.jj2#L99

**Comment by chfw** [comment]
The right number of Blank lines helps reading. Are you sure that you won't read the files yourself?

**Comment by chfw** [comment]
I misunderstood your requirement but it is done now.
