### ISSUE TITLE
Add option to list all variables in all templates

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#130]
It is important to be able to see a list of variables which are available to be set in the yaml, or re-used in new templates.

The new option would load all of the templates, display a list of "template.ext:variable" pairs, and not write any targets.  `--list-template-variables` seems like a good name.

Due to moban supporting many template processors, this will need to be part of the template engine API

For jinja, this is quite easy:

http://jinja.pocoo.org/docs/dev/api/#jinja2.meta.find_undeclared_variables

**Comment by jayvdb** [comment]
Similar upstream jinja2 issue: https://github.com/pallets/jinja/issues/174

SO thread https://stackoverflow.com/questions/26694767/jinja2-variables-in-included-template

And something similar has been built for statik and coala-mobans
https://github.com/thanethomson/statik/pull/105
https://gitlab.com/jayvdb/mobans/commit/3eedcea1ec450599de08b9c3f7cb91739f2acef6

One solution is to add another global `__context__` to hold the dictionary of all variables.  Then moban can have its own/internal templates like `list_template_variables.jj2` which render command line output.

**Comment by PrajwalM2212** [comment]
Another thread: https://stackoverflow.com/questions/8260490/how-to-get-list-of-all-variables-in-jinja-2-templates

**Comment by jayvdb** [comment]
For 0.4.0, ill do this feature without plugin api changes, which will be done in 0.5.0

**Comment by chfw** [comment]
waiting for @jayvdb 's time.

**Comment by chfw** [comment]
Stale issue.
