### ISSUE TITLE
Low setup usage

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#133]
Some alternatives to moban have simplicity on their side.

It should be possible for moban to be easily used in an ad-hoc manner without a config file , like `moban foo.jj2` to generate `foo` using environment variables.

c.f. https://github.com/andreasjansson/envtpl/blob/master/README.md

Or if there is a config file, `moban foo.jj2` would load it and generate `foo` or the target listed in the config if it is present there.

**Comment by chfw** [comment]
yep, can easily do that. 

The reason why it hasn't been done is missing actual use case.

**Comment by chfw** [comment]
@jayvdb @CLiu13 , previously I suggested to inject env to globals. Now, I got another suggestion:

Referencing https://github.com/andreasjansson/envtpl/blob/master/README.md, I think we could do a bit better in the following way:

1) incorporate environment variables as a base data config for all data config files, meaning each data config automatically overrides the environment variable.

for example, scenario 1:

env var:

`export HELLO="TEST"`

test.jj2:
`{{HELLO}}`

moban -t test.jj2

shall simply get

TEST 


scenario 2:

env var:

`export HELLO="TEST"`

data.yml

HELLO: world

test.jj2:
`{{HELLO}}`

moban -t test.jj2

shall simply get

world

2) we may extend our functionality to support

`moban -t "{{HELLO}}" `

and get `moban.output`


#149

**Comment by chfw** [comment]
hmm.. after checking the implementation, item 1 is there :)
