### ISSUE TITLE
Non-zero exit status

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#14]
If there were any modifications, it would be helpful if there was a non-zero status.

This would allow moban to be used in CI to detect (and usually fail) if all files were not in sync.

This could be done like `git diff --exit-code` which adds the exit code to reflect there were changes.

**Comment by chfw** [comment]
what about returning the number of templated files? 0 for no files, 1 for 1 files... n for N files.

**Comment by chfw** [comment]
1 for having and acted on changes, 2 for errors. 

Just checked that N is impossible as the upper limit is 255.

**Comment by chfw** [comment]
please be notified that I have renamed setupmobans to python-mobans
