### ISSUE TITLE
Zero-length format string fields impact Python 2.6 support

### ISSUE THREAD

**Issue by chrahunt** [moremoban/moban#15]
The template strings [here](https://github.com/moremoban/moban/blob/660d37e801d3184f3a2b06d28cf436c0c8565843/moban/reporter.py#L5) are not supported on Python 2.6 without indices in the `{}`.

**Comment by chfw** [comment]
Since python 2.6 is on its way out, python 2.6 is not planned to be supported. But I will fix it so that it can be used in python 2.6 as well.

Please be aware of this table of statues: https://devguide.python.org/#status-of-python-branches

**Comment by chfw** [comment]
the fix is released in 0.1.1.
