### ISSUE TITLE
Empty file base_engine.py

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#158]
The openSUSE rpm linter errors when there is an empty python file, so I needed to delete `base_engine.py` for the rpm, or fill it.  I am fairly confident this rule will also be present in the RedHat rpm linter.

Deleting the file worked fine.

I've now changed that to

```bash
echo '"""Base engine."""' > $RPM_BUILD_DIR/moban-%{version}/moban/base_engine.py
```

It isnt good for the rpm version to be containing different source, but it seems this file isnt used, or isnt critical.  If it is being used somehow, we could include a docstring in the repo, so this workaround isnt needed in the .spec.

**Comment by chfw** [comment]
will release 0.3.8 in a clean folder. 

meanwhile, I am still search for a pipeline for automatic package publishing. travis-ci failed me. azure pipeline is still puzzling me. Not sure how does twine credentials get in azure pipeline.

**Comment by jayvdb** [comment]
https://github.com/Azure/azure-functions-python-library/issues/1 not done, so maybe it isnt easy ;-)

Did you try https://docs.travis-ci.com/user/deployment/pypi/ ?
Another example at http://www.dougalmatthews.com/2016/Sep/01/automate-publishing-to-pypi-with-pbr-and-travis/
