### ISSUE TITLE
Allow binary files

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#16]
Currently binary files cause an error.

They should be detected as non jinja, and copied to the source destination without being templated.

**Comment by chfw** [comment]
So you would like moban to copy files instead.

**Comment by jayvdb** [comment]
Yes.

Possibly these untemplated files could be listed in a different section instead of `targets:`?

**Comment by jayvdb** [comment]
Also a `copy` could be used to copy templates from one repo to another repo, which cant be done atm because moban will apply the template .
i.e. https://gitlab.com/coala/mobans/issues/14

**Comment by chfw** [comment]
Accepted! Will use "copy:". 

1. `copy` is self-explanatory. cannot be more clearer
2. `copy:` as separate, allows pain-free upgrade and incremental development.

**Comment by chfw** [comment]
syntax:

```
copy:
  - "moban/setup.py": setup.py
```

**Comment by jayvdb** [comment]
Another possible keyword instead of `copy` might be `sync`.

But `copy` is ok.  I just thought of another possibility.

I see you've already done some work on this.  I'll do some testing of this asap.

**Comment by jayvdb** [comment]
wfm

**Comment by jayvdb** [comment]
I just noticed that `yehua` uses `configuration: static_path:` and `static:`

Should these concepts be merged?

**Comment by chfw** [comment]
yeah, yehua needed it to copy over template, overlapping with moban's new functionality.
