### ISSUE TITLE
Additional config formats

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#164]
Currently moban only supports yaml as the config format.

[anytemplate](https://pypi.org/project/anytemplate/) uses [anyconfig](https://pypi.org/project/anyconfig/) to support:

- JSON
- ini
- pickle
- xml
- Java properties
- B-sh
- yaml
- toml
- [configobj](https://pypi.org/project/configobj/)

It would probably make sense to define a plugin layer for input data formats, keep the existing yaml as a native plugin, and add a 'anyconfig' plugin which provides supports for all the other formats.

I can see a lot of potential for growth by adding specific file formats, like .spec , and more complex data structures like SPDX license metadata files (so that templates do not need to load large data files).

**Comment by chfw** [comment]
Cannot agree more!

**Comment by chfw** [comment]
all other data config could be written as a built-in module if no external dependencies or as a moban plugin. Hence, case closed.
