### ISSUE TITLE
All copy rules processed when CLI args request single target

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#166]
When moban is invoked with CLI args which request a single target is processed, as improved by https://github.com/moremoban/moban/pull/146 , all copy rules are run anyway.

The quick fix is to not ever process copy rules when a specific template target was specified in the CLI args.

Ideally a copy rule should be considered to be a normal target, and able to be selected using the CLI args.  This will happen automatically if https://github.com/moremoban/moban/issues/165 is done.

**Comment by chfw** [comment]
This is fixed by #165
