### ISSUE TITLE
Do not fetch all branches of remote `requires`

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#172]
When `requires:` are used, all branches are fetched.

This can likely be solved with a simple CLI arg when invoking subprocess `git`.

Note that switching to using GitPython (https://github.com/moremoban/moban/issues/169) would also likely solve this as it wouldnt have the same defaults as the cli `git`.

**Comment by jayvdb** [comment]
(Does the current git integration allow branches to be specified in the `requires:` ?  c.f. https://github.com/moremoban/moban/issues/75)

**Comment by chfw** [comment]
need to change code to squeeze in a bit parameters.

**Comment by chfw** [comment]
wondered if GitPython become integrated, this need could be coded in that code change.
