### ISSUE TITLE
Untested code in mobanfile.py

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#176]
https://codecov.io/gh/moremoban/moban/src/master/moban/mobanfile.py#L44

Are we using these functionalities in red block? I doubted that the exception would ever raise because moban will provide a default output file name if not given.

**Comment by chfw** [comment]
<img width="688" alt="screenshot 2019-01-18 at 07 12 35" src="https://user-images.githubusercontent.com/4280312/51370868-72ae2780-1af0-11e9-9933-26fb8cc7a666.png">

**Comment by jayvdb** [comment]
We should require 100% test coverage, to reduce regressions and new bugs.

**Comment by chfw** [comment]
Fixed by https://github.com/moremoban/moban/issues/178
