### ISSUE TITLE
File exists filter

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#18]
Ansible has a file `exists` filter which would be very helpful for building templates which are based on the files in the repo.

A possible complication is that files may be in `targets` and not yet generated.

**Comment by chfw** [comment]
OK. You have done the home work for me then. I could see that you like the following lines in the MANIFEST.in:

`{% if exists('CHANGELOG.rst'%}include CHANGELOG.rst{%endif%}`

Let me have a thought on this one.

**Comment by jayvdb** [comment]
Ya.  Or `{% if 'CHANGELOG.rst' | exists %}`

Strangely I cant see it in http://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html

But they are listed at https://ansible-manual.readthedocs.io/en/stable-2.3/playbooks_tests.html#testing-paths

**Comment by chfw** [comment]
please wait for next release
