### ISSUE TITLE
CLI: Output only one file

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#180]
`moban -o output` currently processes all files in `targets:`

CLI args should always take precedence of config file.

This is similar to the last sentence of

https://github.com/moremoban/moban/issues/133

**Comment by chfw** [comment]
currently, mobanfile take precedence over cli, meaning if there exists a moban file, moban will process mobanfile. 

Now with the presence of the mobanfile, moban receive a few params, i.e. -o 'single.output', what should moban do?

1) single one output from targets and templating it?
2) report error when 'single.output' is not found?

**Comment by jayvdb** [comment]
CLI should always take precedence over configuration files.

"The user is always right"  they added CLI arguments.  They shouldnt ignored.

**Comment by chfw** [comment]
but with the presence of mobanfile, do you overlap the cli commands with mobanfile, meaning cli command in this case will select things from mobanfile?

the other way of handling cli, is that ignore mobanfile although it is present, then user cli commands must be complete.
