### ISSUE TITLE
Emit error if target appears twice

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#184]
There are some future use-cases for a target appearing twice.  e.g. https://github.com/moremoban/moban/issues/38 , and also splitting targets into multiple files , where it is more likely that two entries might occur.

We need to reject this occurring now, until we have decided how that scenario should be handled.

**Comment by chfw** [comment]
I think sequentially, 1) the latter one shall override the earlier ones or 2) throw an error.

The matching criteria: a. template name, b. config file name, c. output file name are the same. A new class named 'target' may benefit the matching process.

**Comment by chfw** [comment]
I am just wondering if output alone is the sole error emitter, two or more targets produces: 'great.output'

**Comment by jayvdb** [comment]
This issue is about emitting an error now, because repeating a target now is not supported, especially if the target is repeated in `targets` and `copy`.

**Comment by chfw** [comment]
to define 'repeat', would you agree that 'output' field is enough?

**Comment by chfw** [comment]
When I looked at in code, there is an exception guard this error already, https://github.com/moremoban/moban/blame/dev/moban/plugins/strategy.py#L44.

So I am closing it unless the exception does not raise when there are two duplicated targets. 

here is the test case for such a scenario: https://github.com/moremoban/moban/blob/dev/tests/integration_tests/test_command_line_options.py#L327

**Comment by jayvdb** [comment]
Where I encountered this was a copy: and a target: with the same filename.

Now we are deprecating `copy:`, bugs only caused by using `copy:` can be ignored imo.

**Comment by chfw** [comment]
Oh I see. That makes sense. I forgot that copy was separate to targets.
