### ISSUE TITLE
Reduce pin on ruamel.yaml

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#186]
Down to at least 0.15.80, but ideally as low as possible in 0.15.x without breakages.

**Comment by chfw** [comment]
Just a note here that ruamel.yaml 0.15.86 failed at compilation and 0.15.87 worked.

https://travis-ci.org/moremoban/moban/jobs/486801861

**Comment by chfw** [comment]
https://build.opensuse.org/package/show/devel:languages:python/python-ruamel.yaml shows 0.15.87 is available on opensuse
