### ISSUE TITLE
Investigate lower dependencies

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#187]
We should have an explicitly stated reason for each dependency minimum version, so users/packagers know that it is not arbitrary.

And have a CI job which uses the minimum version, to avoid any bugs with specific minimum versions.

And ideally also have a job which uses random versions between minimum and most recent, to flush out any bugs with specific versions.

@pyexcel had a job with minimum version, and maybe had random versions also.

**Comment by chfw** [comment]
GitPython
RueYaml
appdirs

**Comment by jayvdb** [comment]
This may involve moving some pyexcel CI into pypi-mobans.

**Comment by chfw** [comment]
will progress after this PR is merged: https://github.com/moremoban/pypi-mobans/pull/74
