### ISSUE TITLE
Parity: jinja2-cli & jinja-cli

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#188]
https://apps.fedoraproject.org/packages/python-jinja2-cli

Old project https://pypi.org/project/jinja2-cli/#history

----

New project https://pypi.org/project/jinja-cli/#history

Lets try to get them working with us.

**Comment by chfw** [comment]
I think they had support for shell pipe syntax, which moban does not have

**Comment by chfw** [comment]
I have made initial contact: https://github.com/cykerway/jinja-cli/issues/1

**Comment by chfw** [comment]
I have another contact: https://github.com/mattrobenolt/jinja2-cli/issues/74

**Comment by jayvdb** [comment]
We need to add the missing features first.

**Comment by chfw** [comment]
From 0.4.x mile stone, I presume.

**Comment by chfw** [comment]
I guess contact made too early.

**Comment by chfw** [comment]
All done!
