### ISSUE TITLE
Parity: shift

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#195]
https://github.com/andrew-d/Shift/tree/master/shift/engines is an impressive list of engines, and potentially easy to copy as  moban plugins

**Comment by chfw** [comment]
what a co-incidence? our engine interfaces are very similar and they have done it 7 years ago.

**Comment by chfw** [comment]
I swear that I have not looked at it before I refactored our engine interfaces. what they did proved that our engine interface are about just right.

**Comment by chfw** [comment]
Will look at this in 2020

**Comment by chfw** [comment]
With current architecture, it is very easy to write one plugin for moban. The best way forward is: someone who really uses the template type to write the plugin for moban. As of now, I only uses jinja2. So I do not have time to maintain so many plugins.
