### ISSUE TITLE
implement plugins for more data formats

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#196]
https://github.com/ssato/python-anyconfig/tree/master/anyconfig/backend

best approach is creating plugin moban-anyconfig which wraps `anyconfig`.

**Comment by jayvdb** [comment]
Backends with deps configob, toml & yaml.

We dont need yaml. creating separate plugins for toml & configobj may be better.

**Comment by chfw** [comment]
I like this package because it has decent number unit tests. `moban-anyconfig` would work out as minimalist change for us and for them.

**Comment by chfw** [comment]
with pyfilesystem 2, anyconfig seems one step behind
