### ISSUE TITLE
Prompt for missing vars

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#201]
One feature in https://github.com/dasdachs/documents/blob/master/documents/cli.py is asking user for missing vars.

This is blocked by having a engine plugin hook for getting list of variables.

**Comment by chfw** [comment]
My problem is: how does moban know there is var missing? jinja2 may help but what about other templating engines?

Hence, it comes down to the schema. If that's available, it is a generic way to check missing variables.

**Comment by jayvdb** [comment]
This is blocked by https://github.com/moremoban/moban/issues/130 , and does need a generic plugin hook to provide this information.

**Comment by chfw** [comment]
Stale issue
