### ISSUE TITLE
`requires` doesnt understand git ssh remote syntax

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#207]
```
Invalid requirement: 'git@gitlab.com:foo/bar.git'
It looks like a path. File 'git@gitlab.com:foo/bar.git' does not exist.
```

coala uses `git-url-parse~=1.1.0`, and has contributed lots of bugfixes to it.

https://pypi.org/project/git-url-parse/

**Comment by AkshJain99** [comment]
@jayvdb  what actually need to be done here to solve the issue?

**Comment by chfw** [comment]
@AkshJain99 , this will need some code changes in moban. The repo support was started with narrow support(MVP) and can grow in its scope(feature capabilities).
