### ISSUE TITLE
Error if only `copy` exists and no `targets`

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#21]
When only `copy` exists, i.e. targets is not used, the result is:

```
Error: No targets in .moban.yaml
```

**Comment by chfw** [comment]
hasn't thought `targets` would become optional. will code it in.

**Comment by jayvdb** [comment]
I've already done it.

It was a bit of a special case of importing files into a moban 'commons' repo (https://gitlab.com/coala/mobans/merge_requests/8), and may not be needed permanently if I find I need to template something.
