### ISSUE TITLE
template type: ansible line in file

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#217]
https://github.com/flyte/confp/issues/3#issuecomment-458488134

The important part of this is having the template (a regex) as a literal in the target entry, reducing need for a tiny file containing the template.

A partial implementation could be template type regex, and it operates on the target file, which may originate from a 'copy' action.

**Comment by chfw** [comment]
here is the examples: https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html#examples

it meant the template type would accept functional parameters. as of now, template type does not take any extra parameters.

**Comment by chfw** [comment]
so it would require some architectural upgrade.

**Comment by chfw** [comment]
https://moban.readthedocs.io/en/latest/level-18-user-defined-template-types/README.html

Our architecture can cope such a long parameter list but slightly different protocol.

**Comment by chfw** [comment]
done!

https://github.com/moremoban/moban-ansible/tree/master/docs/level-1-line-in-file

**Comment by chfw** [comment]
Further requests, please submit to moban-ansible project.
