### ISSUE TITLE
git clone depth

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#219]
moban doesnt need a complete copy of the history.  It only needs to be able to sync to the latest from each revision.

clone depth should be something like 2 to reduce unnecessary packs being fetched.

**Comment by chfw** [comment]
good idea!

**Comment by chfw** [comment]
when moban tries to update the repos, is this update command right?

`git fetch origin --depth=1` for getting latest head

I assume, if `git pull` would get everything by default.

**Comment by jayvdb** [comment]
Yes
