### ISSUE TITLE
template_types: task 5: document ad-hoc template type

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#238]
this shall document #234 

related to #202

**Comment by chfw** [comment]
I believe you have already done some documentation. Would you consider it done?

**Comment by ayan-b** [comment]
Yes, this can be closed. :)

**Comment by ayan-b** [comment]
I mistakenly pressed `Close and Comment`,-_-  hope you won't mind.

**Comment by chfw** [comment]
Never mind
