### ISSUE TITLE
Join Google SoC?

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#250]
@ayan-b mentioned Google Summer of Code. @jayvdb, are we late in this party?

**Comment by ayan-b** [comment]
There is already some moban related projects in https://github.com/coala/projects repo especially this one: https://github.com/coala/projects/issues/574 .

**Comment by chfw** [comment]
That is a moban enabled project. Can help with any queries :).

**Comment by ayan-b** [comment]
@chfw a mentor invite will be sent in your mail id as mentioned [here](https://github.com/moremoban/moban/blob/dev/setup.py). Is that OK? :smile:

**Comment by chfw** [comment]
replied

**Comment by ayan-b** [comment]
@chfw ,I have submitted the proposal, please review. :smiley:

**Comment by chfw** [comment]
Sure

**Comment by ayan-b** [comment]
@chfw , I have mailed you the link to the proposal. Please give me your feedback.

**Comment by chfw** [comment]
Have now given my feedback.

**Comment by ayan-b** [comment]
Thanks. I have replied. :blush:
