### ISSUE TITLE
Error in moban 0.4.3

### ISSUE THREAD

**Issue by ayan-b** [moremoban/moban#265]
Using moban 0.4.3, we get this error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte` in the coala-mobans repo, although this error does not arise with moban 0.3.3.

CI log:
 - moban 0.3.3: https://gitlab.com/ayan-b/mobans/-/jobs/199587253
 - moban 0.4.3: https://gitlab.com/ayan-b/mobans/-/jobs/199585396

**Comment by chfw** [comment]
0.4.3 read and write

0.3.3 uses shutils to copy.

when reading in, if the file is not encoded in utf-8, this problem will rise.

**Comment by ayan-b** [comment]
That is also what I suspected. So we can by default convert the file to utf-8 in this repo while reading?

**Comment by chfw** [comment]
https://github.com/moremoban/moban/blob/dev/moban/copy/__init__.py

Copy engine should have read with 'rb' flag and ignore encoding. Simple 'open' fuction  should work. 

When saving, it should use 'wb' flag, treating the content as binary throughout the journey within moban.

**Comment by ayan-b** [comment]
Ok, I will send a PR by tonight.

**Comment by ayan-b** [comment]
This error is not yet fixed: https://gitlab.com/ayan-b/mobans/-/jobs/201319687

**Comment by ayan-b** [comment]
@chfw what do you think?

**Comment by chfw** [comment]
I think you have just shifted decoding from copy engine to write function. In python 3, cannot we write bytes directly to a file?

**Comment by chfw** [comment]
And it also means that the unit test case failed to capture the bug.

**Comment by ayan-b** [comment]
By the way, I wonder if we can simply copy using `os` module without reading or writing.

**Comment by ayan-b** [comment]
I will try to solve the issue over the weekend.
