### ISSUE TITLE
giturlparse vs git-url-parse

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#277]
#227 switched from git-url-parse to giturlparse , due to #226 .  Originally added in #207

- https://github.com/retr0h/git-url-parse
- https://github.com/nephila/giturlparse

(There is also a giturlparse.py , the predecessor of giturlparse)

Both install into site-packages `giturlparse`, so it is impossible to have both installed as dependencies.

coala uses git-url-parse, but giturlparse is starting to get maintained.

`python-gilt` switched to git-url-parse https://github.com/metacloud/gilt/commit/673093d4f5c4e6764fd5c54dcdc7a4066918504f
`lancet` switched https://github.com/GaretJax/lancet/commit/7ba7d2ec2879164c6ae22ca4aa2e4278e421811e#diff-b4ef698db8ca845e5845c4618278f29aL17

As a result it is impossible to install  moban in the same environment in the same environment as coala, gilt or lancet.

openSUSE has `git-url-parse` already

However arch has https://aur.archlinux.org/packages/python-giturlparse/

Most distros have neither.

**Comment by jayvdb** [comment]
fwiw, if there are needed features in https://github.com/nephila/giturlparse , not present in https://github.com/retr0h/git-url-parse , coala could switch.

**Comment by jayvdb** [comment]
> coala could switch.

Actually, I suspect this is not true.   retr0h/git-url-parse parses URLs without both `user/repo` which is needed in some parts of coala (the community GCI app?).  nephila/giturlparse rejects them as invalid.

The problem of #226 is that git-url-parse had some bugs.  I suspect https://github.com/retr0h/git-url-parse/issues/29 was raised about one of them.  That bug was fixed, but the issue has been disappeared by @retr0h.  I see it still doesnt support trailing slashes, which is also another problem with the same scenario.

It has not tests for trailing slashes either. https://travis-ci.org/jayvdb/git-url-parse/builds/555748106  It has 21 parsing test cases.

However, giturlparse also doesnt support trailing slashes; except it does return something which can be manipulated to be correct.

And it also had no tests for trailing slashes.  https://travis-ci.org/jayvdb/giturlparse/builds/555755629  .  It has 11 parsing test cases.

There are *lots* of cases from git-url-parse which fail on giturlparse.  Some are intentional failures.

OTOH, wrt https://github.com/retr0h/git-url-parse , @retr0h has disabled the GitHub issues feature.  That is a *major* problem, especially as the issues are mentioned in the source code, so we need to guess what issues were created by whom, and what they said.

There were also a few nephila/giturlparse test cases which failed on retr0h/git-url-parse, so I have created two PRs.  https://github.com/retr0h/git-url-parse/pull/38 and https://github.com/retr0h/git-url-parse/pull/39

**Comment by jayvdb** [comment]
https://github.com/moremoban/pypi-mobans/commit/eedde0f4e also refers to https://github.com/retr0h/git-url-parse/issues/29 , so I am fairly confident it was created by someone from @coala / @moremoban

**Comment by retr0h** [comment]
Send me PRs to @git-url-parse and I'll merge them.
