### ISSUE TITLE
Check source and target are not the same

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#28]
This is especially relevant for `copy:`, but also possible for `targets:`.

https://github.com/coala/coala-bears/commit/51441bd44387dcd7d0e9ea6da4de4c49f2bb2284 added;
```yaml
.ci/run_with_env.cmd: run_with_env.cmd
```

when `.ci/` was in the template dirs, so the replacement was templating from the source file.  As there was no jinja in that file, it copied identically every time, overwriting itself with itself.

```
configuration:
  template_dir:
    - .moban.dt/
    - .ci/
```

**Comment by chfw** [comment]
There exists such a functionality for targets. will transfer it over to copy function.

**Comment by chfw** [comment]
HashStore is the answer.

**Comment by jayvdb** [comment]
Probably worth making 'copy' a builtin template engine.
