### ISSUE TITLE
ruamel.yaml dependency on Python 3.8-dev should be maintainable or disabled

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#289]
Travis job for 3.8-dev was removed in ec48af448

Following on from https://github.com/moremoban/moban/issues/274 , it is quite likely that there will be another breaking change Cpython 3.8, or in Cython on CPython 3.8, requiring ruamel.yaml to be updated otherwise it fails.

If we add dependency `ruamel.yaml>=0.15.98;python_version == '3.8'`, the minreqs version is `ruamel.yaml==0.15.98;python_version == '3.8'`, and that *will* fail before Python 3.8 is finally released.

Removing the MINREQ Python 3.8-dev job is one option. Currently the .travis template job matrix doesnt support customisation.  The template has other problems too https://github.com/moremoban/pypi-mobans/issues/95

Another approach is for the requirement of ruamel.yaml to be `hg+https://bitbucket.org/ruamel/yaml#egg=ruamel.yaml;python_version == '3.8'`, so that the latest version is always used, preventing caching , but
1. this doesnt work in `setup.py` where `setup_use_markers` mode *is* enabled, at least with old setuptools, as the extra name should be `ruamel.yaml` and `dependency_links` used for URLs.
2. it also *probably* doesnt work in `setup.py` where `setup_use_markers` mode *is not* enabled, for similar reasons as above.

coala-mobans has some template voodoo to help with the above, but it will take time to get that across into pypi-mobans.

Another, possibly simpler approach, is for minreqs template to omit pins for 3.8.  Then the builds should pass as soon as ruamel.yaml releases a new version, and usually he is quite quick in doing releases.

**Comment by chfw** [comment]
released in 0.5.0

**Comment by jayvdb** [comment]
This is a post-0.5.0 problem which still exists.

**Comment by chfw** [comment]
stale issue
