### ISSUE TITLE
-t ignored if .moban.yml file present

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#30]
See https://travis-ci.org/jayvdb/pypi-mobans/jobs/388096764#L456

```console
$ moban -c config/data.yml -t test.file -td templates .
Templating gitignore.jj2 to .gitignore
Templated 1 files.
Everything is up to date!
```

**Comment by chfw** [comment]
it seems config/data.yml will override the common data file in moban file.

**Comment by chfw** [comment]
https://github.com/moremoban/moban/blob/bug-fix-30/tests/integration_tests/test_command_line_options.py#L126

vs

https://github.com/moremoban/moban/blob/bug-fix-30/tests/integration_tests/test_command_line_options.py#L111
