### ISSUE TITLE
python 2 deprecation!

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#303]
Shall we drop python 2 support beyond 2020?

**Comment by chfw** [comment]
related to #302, where python filesystem 2 demands unicode file path in python 2.

**Comment by chfw** [comment]
https://travis-ci.org/moremoban/moban/jobs/562319080

unicode break flake8

**Comment by chfw** [comment]
pysetup can be considered

https://pysetup.readthedocs.io/en/latest/tutorial.html#installing-pysetup

**Comment by chfw** [comment]
`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.`

**Comment by chfw** [comment]
```
GitPython requires Python '>=3.0, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 2.7.13
```

https://travis-ci.org/moremoban/moban/jobs/564152254

**Comment by chfw** [comment]
there are files python GitPython. So not sure why pypy2.7-6.0 would complain

https://pypi.org/project/GitPython/#files

**Comment by jayvdb** [comment]
We should cut a branch for Python 2 support and do a final release with Python 2 support, before removing support.

We can use multiple pins, like done with ruamel.yaml, to install older versions that support Python 2 only when required.

**Comment by chfw** [comment]
Please note this thread too: https://github.com/PyFilesystem/pyfilesystem2/issues/317

**Comment by chfw** [comment]
this will be a priority in 0.7.0, in which python 3.7 only codes will be introduced, such as typing, f-string and data classes. multi-processing via asyncio are under consideration too.

**Comment by jayvdb** [comment]
I dont see a problem with py27 deprecation.

If desupporting an old Python, please ensure that the setup.py uses `python_requires` so that users on other py versions can keep using the older versions of moban without disruption.
