### ISSUE TITLE
Only run minreq jobs on branches

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#309]
The minreq=1 jobs slow down PR's.

The should only run on branches, and ideally only run on dev & master.

That way if there are any minreq problems, they are noticed before release, but dont inhibit development.

**Comment by jayvdb** [comment]
This is complicated to do with .travis.yml , and ideally it is a feature of the travis template, not a local hack.
coala also will need it.

**Comment by chfw** [comment]
https://github.com/moremoban/moban/pull/374
