### ISSUE TITLE
Python 3.5-7 breaking after ruamel version update.

### ISSUE THREAD

**Issue by chay2199** [moremoban/moban#319]
ref: 
test 3.5 - https://gitlab.com/coala/mobans/-/jobs/276980655
test 3.6 - https://gitlab.com/coala/mobans/-/jobs/276980929
test 3.7 - https://gitlab.com/coala/mobans/-/jobs/276981051

**Comment by chay2199** [comment]
Setting an upper limit (<= 0.16.0) to ruamel version is one way to solve the issue. If that is a suitable solution then I would love to solve this issue.

**Comment by chfw** [comment]
Can you please contact ruamel owner about this issue? Meanwhile, can your build pin down ruamel version? It is possible to install a good version before installing moban, then pip wont take latest.

It will be slow to get a response from moban because next release 0.6.0 will take some time.

**Comment by jayvdb** [comment]
I've raised https://bitbucket.org/ruamel/yaml.clib/issues/1/minimum-version-of-setuptools-3825

@ruamel uses a template for all the `ruamel.*` packages, so the same bug likely affects them all, but in the case of `ruamel.yaml.clib` the setup.py is at least out of sync with the template used in `ruamel.yaml`.

**Comment by jayvdb** [comment]
Created https://gitlab.com/coala/mobans/issues/124 for @coala 's problem
