### ISSUE TITLE
Time to drop legacy moban file syntax in 0.7.x?

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#361]
- [ ] `copy` tag
- [ ] `requires` tag
- [ ] old pypi syntax
- [ ] old git syntax

**Comment by chfw** [comment]
The question is: has the downstream system migrated yet? otherwise, pinning on lower version for the time being.

**Comment by jayvdb** [comment]
> The question is: has the downstream system migrated yet?

https://gitlab.com/coala/mobans/ hasnt updated.

**Comment by chfw** [comment]
Yep, will defer this motion indefinitely.

**Comment by chfw** [comment]
pypi-mobans-pkg v0.0.13 has remove its support for:

```
requires:
  - pypi-mobans-pkg
```
