### ISSUE TITLE
Travis CI build error

### ISSUE THREAD

**Issue by reibelj** [moremoban/moban#363]
Currently the Travis CI build does not run due to an error. The error is within the travis.yml file and is due to the structure and configuration of the deploy function.

**Comment by reibelj** [comment]
I will be working on this issue with another group of students as part of course that requires contributing to open source software. If there are any questions or concerns I have joined the gitter channel and can be reached there.

**Comment by chfw** [comment]
Yes, it is an upstream problem.

**Comment by chfw** [comment]
Upstream project is pypi-mobans
