### ISSUE TITLE
OSError: File coala.yaml does not exist

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#365]
There has been some regression, or some functionality has been decommissioned.

https://gitlab.com/jayvdb/package_manager/-/jobs/498590570

The structure is https://gitlab.com/coala/package_manager/-/blob/5f33f1f9/.moban.yaml is used first , and it overrides https://gitlab.com/coala/package_manager/-/blob/5f33f1f9/pm-requirements.yaml , which overrides coala.yaml , which was previously found via `configuration_dir: ../coala-mobans` from `.moban.yaml`.

The same structure is used throughout all coala repos CI, so this halts development until fixed somehow.  If we need to update the syntax, it is possible but a large task and a bit undesirable.

**Comment by chfw** [comment]
it seems to me that coala.yaml file was not available in current directory.

overrides uses file system 2 syntax to refer to file link, here is an example:

`overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"`

**Comment by chfw** [comment]
which version works? I suspect the ones before file system 2 integration.

**Comment by jayvdb** [comment]
coala.yaml isnt in the current directory of https://gitlab.com/coala/package_manager . https://gitlab.com/coala/mobans/  is fetched prior to invocations of moban, and placed in the appropriate directory, so that coala.yaml can be found.

This worked in v0.5.0 at least; im not sure which versions after that worked.

> overrides uses file system 2 syntax to refer to file link

I know about the new features.  Is the system I am using no longer going to be supported?
I do not see a changelog entry which indicates that it is not supported.

**Comment by chfw** [comment]
I will find a time to provide backward compatibility.

**Comment by chfw** [comment]
reproduced. 0.6.4 still worked.

**Comment by chfw** [comment]
Latest 0.7.1 will work for you.

**Comment by chfw** [comment]
if possible, please contribute a regression test for your use case.
