### ISSUE TITLE
Invalid Travis yaml

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#366]
> There was an error in the .travis.yml file from which we could not recover.

> The `deploy` configuration should be a hash (dictionary), or an array of hashes.

https://travis-ci.org/github/jayvdb/moban/jobs/677183910

**Comment by jayvdb** [comment]
The 'false' defaults now also fail.
https://travis-ci.org/github/jayvdb/moban/jobs/677187833

**Comment by chfw** [comment]
yes, I noticed it too.

**Comment by chfw** [comment]
Please try sync with latest pypi-moban. I think I have fixed it. pyexcel project is now green.
