### ISSUE TITLE
Exceptions on malformed yaml

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#37]
I forgot to add a template after a target

```yaml
targets:
  - .gitignore:
```

And got

```py
  File "/home/jayvdb/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 27, in split_template_path
    for piece in template.split('/'):
AttributeError: 'NoneType' object has no attribute 'split'
```

I suspect there are a few other similar cases of exceptions when given malformed yaml.  moban should explain which line is broken and why.

**Comment by chfw** [comment]
Yes it will be user friendly

**Comment by seeeturtle** [comment]
@jayvdb @chfw 
To report the exact position where it's wrong, yaml parser that supports line number is required.
However, `pyyaml` doesn't supports the feature. I can do some hacky things to make it support,
but there is already better library `ruamel.yaml` that supports it.
Is it ok to use `ruamel.yaml` instead of `pyyaml`?
Or should I do the hacky job?

**Comment by chfw** [comment]
looking from ruamel.yaml's change log and overview, it looks better. My instance is: if our unit tests above passes, I would give ruame.yaml a go.

**Comment by seeeturtle** [comment]
yup, it passes the test.
I'll work with the ruamek.yaml

**Comment by chfw** [comment]
Interesting, pyyaml can denote error location

```
  File "/Users/jaska/github/moremoban/moban-env/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!copy'
  in ".moban.yml", line 5, column 5
```

pyyaml==3.13

**Comment by seeeturtle** [comment]
Yeah, pyyaml shows that in doc. It's quite strange that pyyaml doesn't give that to dev.

**Comment by chfw** [comment]
Meaning to the exception?

**Comment by seeeturtle** [comment]
i mean that pyyaml doesn't give location in general, even though they provide it in exception.

**Comment by seeeturtle** [comment]
Hmm... i've read pyyaml api and it seems to provide point of each element but not so convenient.
it provides some kind of ast for yaml file and tokens. they have location properties.
