### ISSUE TITLE
Option on CLI to output results to stdout

### ISSUE THREAD

**Issue by salotz** [moremoban/moban#390]
This should at least be an option, perhaps even default behavior (over making a `moban.output` file).

**Comment by chfw** [comment]
apparently, you need this little option. I will code it in.

**Comment by salotz** [comment]
Much appreciated! Moban templates in shell pipelines will be pretty awesome.

**Comment by chfw** [comment]
please let me know your feedback on this.

**Comment by salotz** [comment]
Looks awesome! Works perfectly so far for me. Great work!
