### ISSUE TITLE
Rendered content output to stdout twice

### ISSUE THREAD

**Issue by salotz** [moremoban/moban#393]
This only happens when the template is coming from a file. For instance this works as intended:

```
--> HELLO="hello there" moban "Here is my greeting: {{HELLO}}"
Here is my greeting: hello there
```

But if you are getting it from a file for example `template.txt.jj2`:

```
{{HELLO}}
```

where `data.yaml` is:

```
HELLO: "hello there"
```

These result:

```
--> moban -c data.yaml -t example.txt.jj2
hello there
hello there

--> HELLO="hello there" moban -t example.txt.jj2
hello there
hello there
```

I have a fix, just prepping the PR.

**Comment by chfw** [comment]
yep, well spotted. I look forward to your update.
