### ISSUE TITLE
Template type: Haml

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#53]
http://haml.info

https://github.com/jessemiller/HamlPy compiles to django, so that would need to be added first.

Lots of partial solutions.

**Comment by jayvdb** [comment]
Jinja extension for this language https://github.com/grigi/jinja2-hamlpy

**Comment by jayvdb** [comment]
Ayan, this would be a good layer on top of your jinja extensions work

**Comment by ayan-b** [comment]
@jayvdb @chfw Done, I am transferring the repo here.
