### ISSUE TITLE
Template type: Slim

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#54]
http://slim-lang.com

https://github.com/avanov/Plim built on top of mako. Not actively maintained.

**Comment by jayvdb** [comment]
A jinja2 extension for this:

https://github.com/thoughtnirvana/slimish-jinja2

**Comment by jayvdb** [comment]
https://github.com/CLiu13/moban-slim needs to be moved under the moremoban org.

If you dont have rights for that transfer @CLiu13 , let us know.

**Comment by CLiu13** [comment]
Has been transferred to https://github.com/moremoban/moban-slim.
