### ISSUE TITLE
moban jinja2 repository

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#6]
It would be helpful to have a shared repository of jinja2 templates, consisting of many of the files in https://github.com/pyexcel/pyexcel-commons/tree/master/templates which are re-usable for other purposes.

I see you've built `yehua`, which somewhat 'centralises' some of these files, but not all, and many people may only want one template without yehua-ifying everything.

**Comment by chfw** [comment]
It can be helpful if an generic set will extracted for general public usage. And pyexcel-commons would shrink too. Let me find a time slot to organise this.

As to the yehua folder in pyexcel-commons, they are the seed for any pyexcel projects. Yehua got is own minimal sets when it runs by itself. I am yet to complete its documentation and release it to pypi.

**Comment by chfw** [comment]
Let's continue the discussion [here](https://github.com/moremoban/setupmobans)
