### ISSUE TITLE
Remove duplicated lines from output

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#60]
A simpler version of https://github.com/moremoban/moban/issues/36 is when the modelines are identical, subsequent ones can be removed.

This will also help with the gitignore includes, as sometimes the same rule appears in multiple included files.

This might be best done as a Jinja extension.

**Comment by chfw** [comment]
The way to deduplicate varies. 

https://github.com/moremoban/moban/tree/dev/tests/regression_tests/level-7-b-template-engine-plugin outlines one way to implement the de-duplication.

**Comment by chfw** [comment]
https://github.com/moremoban/moban/blob/dev/tests/regression_tests/level-7-b-template-engine-plugin/custom-plugin/deduplicate.py
