### ISSUE TITLE
Groups of targets

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#62]
I need to be able to regenerate only three of the targets which need to be in sync, where the complete list contains many more targets which should not be updated.

I could manually invoke moban three times.

But it would be better to add labels to targets, so they can be grouped together.

**Comment by chfw** [comment]
yes, label can be added but don't forget moban have a command line interface too so it will take a while to get it right. 

What about the alternative: create three moban file and use `moban -m group1.yml`, `moban -m group2.yml` and `moban -m group3.yml`

**Comment by jayvdb** [comment]
Possibly we can have three separate mobanfile , and then a global mobanfile which overrides all three to use moban's yaml merging feature.

**Comment by chfw** [comment]
A few more changes could enable this grouping feature. 

1. Enable cli to execute a group key
2. Allow non template type name as group key.

**Comment by chfw** [comment]
Current implementation can be found at level 16.
