### ISSUE TITLE
Template type: patch

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#75]
This template type is a bit strange ...

It would take a patch file, possibly only unified diff loaded using `unidiff`, and effectively `include` the source files mentioned in the patch and apply the diff.

**Comment by chfw** [comment]
I am lost on this issue.

**Comment by chfw** [comment]
do you mean template engine for "a.patch"?

**Comment by jayvdb** [comment]
> do you mean template engine for "a.patch"?

Yes.

At least initially it would be ok for the patch to only include changes for a single file.

The patch plugin would get the path of the old file in the patch header, and find that file in the sources (i.e. `template_dir:`) like the copy engine currently does.  It would then apply the patch against that file to generate the target.

**Comment by jayvdb** [comment]
Note this is less important now that moban has git integration, as the same objective could usually be achieved by forking a source repo and putting the patch on a branch. (Does the current git integration allow branches to be specified in the `requires:` ?)

The remaining use-case is offline use, or where the source isnt in git, such as packaging, which consist of a tarball and lots of patches.
