### ISSUE TITLE
Add jinja2 extensions

### ISSUE THREAD

**Issue by jayvdb** [moremoban/moban#90]
Especially helpful is statement support, aka `do`

http://jinja.pocoo.org/docs/2.10/extensions/#expression-statement

Loop Controls would also be nice syntax to have available.

https://github.com/duelafn/python-jinja2-apci looks very helpful for debugging, and for intentionally breaking templates when backwards compatibility is not possible.

https://github.com/wewearglasses/jinja2-required-variables-extension looks great for performance improvements.

https://github.com/zehome/jinja2-commentif looks good for adding comments without the hash prefix which is a keyword in jinja2

https://github.com/tlatsas/jinja2-highlight would be great for documentation.

While very basic, it would also by good to add https://pypi.org/project/jinja2-git/ , and add new git based information to that extension.

Likewise https://pypi.org/project/jinja2-github/ and https://github.com/hackebrot/jinja2-time 

https://github.com/stanfeldman/compressinja looks interesting.

https://github.com/danielchatfield/jinja2_markdown or https://github.com/nrsimha/jingo-markdown might be better as an optional moban extension.

https://github.com/jpscaletti/jinja-includewith is a nice syntax improvement

Note to self: see if https://github.com/mankyd/jinjatag is still usable.

**Comment by jayvdb** [comment]
Perhaps we need some way to enable jinja extensions in the moban yaml.  That way people can choose which ones they need.

But enabling expression-statement and loop-controls by default seems sensible.  Extra features for free.

**Comment by jayvdb** [comment]
https://pypi.org/project/jinja2-pimport/ exposes all of python to the templates.

**Comment by jayvdb** [comment]
https://github.com/thanethomson/statik/issues/6 shows jinja extensions being configurably added by a tool with a similar ethos.

**Comment by ayan-b** [comment]
I was trying to solve the issue. The user adds the required extensions in the yaml or mobanfile, something like:
```
extensions:
  - jinja2.ext.do
  - jinja2.ext.loopcontrols
```
And I am passing the list of extensions through BaseEngine, _i.e._,
`BaseEngine(template_dirs, context_dirs, engine_cls, extensions)`. But this clearly breaks all the tests which use `BaseEngine`. As can be found from the [docs](https://jinja.pocoo.org/docs/2.10/extensions/), the extensions need to be passed while declaring the environment. So, is there any other way to pass extensions without breaking BaseEngine?

**Comment by chfw** [comment]
@ayan-b can you help contribute some docs for extensions? for it to go out, as my personal convention, it needs some thing like this: `docs/level-12-specify-engine-extensions`. This doc should be readable and testable. In tests/test_docs.py, there exists all docs test commands.

My extensions work lives in `extensions` branch

**Comment by ayan-b** [comment]
> @ayan-b can you help contribute some docs for extensions? for it to go out, as my personal convention, it needs some thing like this: `docs/level-12-specify-engine-extensions`. This doc should be readable and testable. In tests/test_docs.py, there exists all docs test commands.
> 
> My extensions work lives in `extensions` branch

Sure.

**Comment by jayvdb** [comment]
Note https://build.opensuse.org/package/show/devel:languages:python/python-jinja2-time already exists, also https://apps.fedoraproject.org/packages/python-jinja2-time

And more at https://apps.fedoraproject.org/packages/s/Jinja

**Comment by jayvdb** [comment]
Can we have some docs showing / testing use with jinja2-time and https://github.com/duelafn/python-jinja2-apci

**Comment by ayan-b** [comment]
I am solving https://github.com/moremoban/moban/issues/202 first and will make a PR related to this once https://github.com/moremoban/moban/issues/202 is merged.

**Comment by jayvdb** [comment]
I think jinja extensions could be part of the 'options' mapping.

**Comment by chfw** [comment]
Any more change for this issue?

**Comment by ayan-b** [comment]
> Any more change for this issue? Since we have already added extensions support.

We need to dynamically import the extension for example `import jinja2_time`.

**Comment by chfw** [comment]
Dynamic import could be achieved easily.

**Comment by chfw** [comment]
why jinja2_time should be imported whereas jinja2.ext.loop shall not? Is there a natural rule that we can code it up?

**Comment by ayan-b** [comment]
> why jinja2_time should be imported whereas jinja2.ext.loop shall not? Is there a natural rule that we can code it up?

Yup, for example, the extensions are: `jinja2_time.TimeExtension` and `jinja2.ext.do`, then we need to import `jinja2_time` and `jinja2`, Since, `jinja2` is already imported, we need not to import it once again.

I am sending a PR related to this.

**Comment by chfw** [comment]
since 0.6.2, `moban -e jinja2=your_custom_jinja2_extension `will load your custom jinja2 extension as well

**Comment by chfw** [comment]
practical usage of `-e`: https://github.com/chfw/math-sheets/blob/master/reception/a_op_b_op_c/make.sh

**Comment by chfw** [comment]
Here is the documentation on it: https://moban.readthedocs.io/en/latest/level-12-use-template-engine-extensions/README.html

**Comment by chfw** [comment]
since 0.8.2, the extended syntax below, will activate ad-hoc filter, test and global of your choice.
```
moban -e jinja2=filter:moban.externals.file_system.url_join \
         jinja2=test:moban.externals.file_system.exists \
         jinja2=global:description=moban.constants.PROGRAM_DESCRIPTION \
      -t "{{ 'a'|url_join('b')}} {{'b' is exists}} {{description}}`
