### ISSUE TITLE
Developer guide

### ISSUE THREAD

**Issue by chfw** [moremoban/moban#99]
Virtualenv --no-site-packages mobanvenv
Source mobanvenv
Pip install -r requirements.txt
Pip install -r tests/requirements.txt
Make

To make documentation update, do

Make update

Note: please ignore capital letters in each command.

**Comment by ayan-b** [comment]
We already have a Contributing file similar to this. I guess this can be closed. https://github.com/moremoban/moban/blob/dev/CONTRIBUTING.md
